name: dump context

run-name: dump context

on: pull_request

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            console.log(context.payload.pull_request.base)
            console.log(context.payload.pull_request.head)